[[redirects]]
  from = "https://verdant-haupia-6196e0.netlify.app/api/auth"
  to = "https://sore-erin-wasp-gown.cyclic.app/api/auth"
  status = 200
  force = true

[[redirects]]
  from = "https://verdant-haupia-6196e0.netlify.app/api/contacts"
  to = "https://sore-erin-wasp-gown.cyclic.app/api/contacts"
  status = 200
  force = true

[[redirects]]
  from = "https://verdant-haupia-6196e0.netlify.app/api/users"
  to = "https://sore-erin-wasp-gown.cyclic.app/api/users"
  status = 200
  force = true
